SELECT CODS, CURS, NOTA, AN, TAXA FROM NOTE;

SELECT NUME,
       PRENUME 
FROM STUDENT
WHERE DATA_SFARSIT IS NULL;

SELECT * FROM NOTE

ALTER TABLE NOTE
ALTER COLUMN TAXA DECIMAL(7,2);

SELECT S.NUME ,
       S.PRENUME
FROM STUDENT AS S INNER JOIN NOTE AS N ON
S.CODS = N.CODS 
WHERE TAXA >0;

/*
SELECT S.NUME ,
       S.PRENUME
FROM STUDENT AS S ,
     NOTE AS N
WHERE
S.CODS = N.CODS AND
TAXA >0;
*/

SELECT S.NUME, N.NOTA, N.CURS
FROM STUDENT AS S INNER JOIN NOTE AS N ON
S.CODS = N.CODS;

SELECT DISTINCT S.PRENUME
FROM STUDENT AS S ;

SELECT S.PRENUME, COUNT (S.PRENUME) AS NR_APARITII
FROM STUDENT AS S 
GROUP BY S.PRENUME;

SELECT N.NOTA
FROM STUDENT AS S INNER JOIN NOTE AS N ON 
S.CODS = N.CODS 
WHERE S.PRENUME = 'Tiberiu' and S.NUME = 'Radu';

SELECT N.TAXA + 100000
FROM NOTE AS N;

SELECT N.TAXA - N.TAXA/4, N.TAXA, N.TAXA*0.75
FROM NOTE AS N;

SELECT N.TAXA + N.TAXA*1/10, N.TAXA, N.TAXA*1.1
FROM NOTE AS N;

UPDATE NOTE 
SET TAXA =TAXA*1.1
WHERE CODS IN (SELECT CODS FROM STUDENT WHERE PRENUME='Tiberiu' and NUME = 'Radu');

SELECT NUME + ' ' + PRENUME AS NUME_COMPLET
FROM STUDENT

SELECT S.NUME, S.PRENUME
FROM STUDENT AS S INNER JOIN NOTE AS N ON
S.CODS=N.CODS
WHERE N.AN = 1;

ALTER TABLE NOTE
DROP COLUMN TAXA;

ALTER TABLE NOTE
ADD TAXA DECIMAL(7,2);

UPDATE NOTE
SET TAXA = 10;

UPDATE NOTE 
SET TAXA =TAXA*1.1
WHERE CODS IN (SELECT CODS FROM STUDENT WHERE PRENUME='Matei' );

SELECT N.TAXA
FROM STUDENT AS S INNER JOIN NOTE AS N ON
S.CODS = N.CODS
WHERE S.PRENUME='Matei';








