CREATE DATABASE SITUATIE;
COMMIT;
USE SITUATIE;

CREATE TABLE STUDENT(
CODS varchar(5) PRIMARY KEY,
NUME varchar(15),
PRENUME varchar (25),
DATA_INCEPUT DATE,
DATA_SFARSIT DATE,
SITUATIE varchar(1),
INV varchar(1),
SEX varchar(1) DEFAULT ('B') CHECK ( SEX= 'B' or SEX='F') 
);

CREATE TABLE NOTE(
CODS varchar(5) FOREIGN KEY REFERENCES STUDENT(CODS),
CURS varchar(15) NOT NULL,
NOTA DECIMAL(4,2),
AN varchar(1) NOT NULL,
TAXA int,
PRIMARY KEY (CODS,CURS,AN)
);

INSERT INTO STUDENT(CODS, NUME, PRENUME, DATA_INCEPUT, DATA_SFARSIT, SITUATIE, INV, SEX)
VALUES (001, 'Banu', 'Andrei', '1990-10-01', '1995-06-15' , 'B', 'Z', 'B');

INSERT INTO STUDENT(CODS, NUME, PRENUME, DATA_INCEPUT, DATA_SFARSIT, SITUATIE, INV, SEX)
VALUES (002, 'Manta', 'Andrei', '2010-10-01', NULL , 'B', 'S', 'B');

INSERT INTO STUDENT(CODS, NUME, PRENUME, DATA_INCEPUT, DATA_SFARSIT, SITUATIE, INV, SEX)
VALUES (003, 'Dima', 'Cristina', '1992-10-01', '1997-06-15' , 'N', 'Z', 'F');

INSERT INTO STUDENT(CODS, NUME, PRENUME, DATA_INCEPUT, DATA_SFARSIT, SITUATIE, INV, SEX)
VALUES (004, 'Stroie', 'Camelia', '1995-10-01', '2000-06-15' , 'N', 'S', 'F');

INSERT INTO STUDENT(CODS, NUME, PRENUME, DATA_INCEPUT, DATA_SFARSIT, SITUATIE, INV, SEX)
VALUES (005, 'Radu', 'Tiberiu', '2009-10-01', NULL , 'N', 'S', 'B');

INSERT INTO STUDENT(CODS, NUME, PRENUME, DATA_INCEPUT, DATA_SFARSIT, SITUATIE, INV, SEX)
VALUES (006, 'Dima', 'Carmen', '2010-10-01', NULL , 'B', 'Z', 'F');

INSERT INTO STUDENT(CODS, NUME, PRENUME, DATA_INCEPUT, DATA_SFARSIT, SITUATIE, INV, SEX)
VALUES (007, 'Stoie', 'Aurelia', '2005-10-01', '2009-06-15' , 'B', 'S', 'F');

INSERT INTO STUDENT(CODS, NUME, PRENUME, DATA_INCEPUT, DATA_SFARSIT, SITUATIE, INV, SEX)
VALUES (008, 'Manta', 'Silviu', '2008-10-01', NULL , 'N', 'Z', 'B');

INSERT INTO NOTE (CODS,CURS,NOTA,AN,TAXA)
VALUES (005,'Fizica', 6, 1, 35.5);

INSERT INTO NOTE (CODS,CURS,NOTA,AN,TAXA)
VALUES (005,'Chimie', 5, 1, NULL);

INSERT INTO NOTE (CODS,CURS,NOTA,AN,TAXA)
VALUES (002,'Fizica', 10, 1, 0);

INSERT INTO NOTE (CODS,CURS,NOTA,AN,TAXA)
VALUES (002,'Chimie', 9, 1, 25.75);

INSERT INTO NOTE (CODS,CURS,NOTA,AN,TAXA)
VALUES (005,'Istorie', 7, 1, 35.5);

INSERT INTO NOTE (CODS,CURS,NOTA,AN,TAXA)
VALUES (005,'Engleza', 7, 1, NULL);

INSERT INTO NOTE (CODS,CURS,NOTA,AN,TAXA)
VALUES (006,'PC I', 10, 1, NULL);

INSERT INTO NOTE (CODS,CURS,NOTA,AN,TAXA)
VALUES (006,'PC II', 9, 1, NULL);

DELETE FROM NOTE WHERE CODS = 006;

INSERT INTO NOTE (CODS,CURS,NOTA,AN,TAXA)
VALUES (006,'PC I', 10, 1, NULL);

INSERT INTO NOTE (CODS,CURS,NOTA,AN,TAXA)
VALUES (006,'PC II', 9, 1, NULL);

ALTER TABLE STUDENT
ADD JUD VARCHAR(2);

UPDATE STUDENT
SET JUD = 'BV'
WHERE CODS = 001;

UPDATE STUDENT
SET JUD = 'BV'
WHERE CODS = 002;

UPDATE STUDENT
SET JUD = 'CJ'
WHERE CODS = 003;

UPDATE STUDENT
SET JUD = 'BC'
WHERE CODS = 004;

UPDATE STUDENT
SET JUD = 'IS'
WHERE CODS = 005;

UPDATE STUDENT
SET JUD = 'BV'
WHERE CODS = 006;

UPDATE STUDENT
SET JUD = 'CV'
WHERE CODS = 007;

UPDATE STUDENT
SET JUD = 'BV'
WHERE CODS = 008;

DROP TABLE NOTE;

CREATE TABLE NOTE(
CODS varchar(5) FOREIGN KEY REFERENCES STUDENT(CODS),
CURS varchar(15) NOT NULL,
NOTA DECIMAL(4,2),
AN varchar(1) NOT NULL,
TAXA int,
PRIMARY KEY (CODS,CURS,AN)
);


